//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
//                FILE: BUTTONS.H
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#ifndef __APPMOTOR_H__
#define __APPMOTOR_H__

extern uint8_t brakeState;
#define BRAKESTATE_RESET		0
#define BRAKESTATE_IDLESLEEP	1
#define BRAKESTATE_POWERINGUP	2
#define BRAKESTATE_PRESETUP		3
#define BRAKESTATE_PRESETUP0	28
#define BRAKESTATE_WAITONSETUP	4
#define BRAKESTATE_WAITONSETUPLOADCELL 29
#define BRAKESTATE_SETUPACTIVE	5
#define BRAKESTATE_POWEREDUP	6
#define BRAKESTATE_POWEREDUP0	27
#define BRAKESTATE_ERROR_RETRACT 7
#define BRAKESTATE_ERROR		8
#define BRAKESTATE_ERRORLOAD	31
#define BRAKESTATE_ERRORLOADWAIT	32
#define BRAKESTATE_ACTIVE		9
#define BRAKESTATE_ACTIVELOAD	30
#define BRAKESTATE_ACTIVE_EXTEND		10
#define BRAKESTATE_HOLDOFF_ACTIVE		11
#define BRAKESTATE_ACTIVE_RETRACT		12
#define BRAKESTATE_ACTIVE_HOLD			13
#define BRAKESTATE_HOLDOFF_ACTIVEFROMSETUP	34
#define BRAKESTATE_SETUPACTIVE_PAUSE_EXTEND 14
#define BRAKESTATE_SETUPACTIVE_PAUSE_RETRACT 15
#define BRAKESTATE_END_RETRACT				16
#define BRAKESTATE_ACTIVE_EXTEND_BREAKAWAY	17
#define BRAKESTATE_ACTIVE_HOLD_BREAKAWAY	18
#define BRAKESTATE_END_RETRACT_BREAKAWAY	19
#define BRAKESTATE_ACTIVE_EXTEND_MANUAL		20
#define BRAKESTATE_ACTIVE_HOLD_MANUAL		21
#define BRAKESTATE_END_RETRACT_MANUAL		22
#define BRAKESTATE_END_RETRACT_TIMEOUT	23
#define BRAKESTATE_ERROR_FINAL			24
#define BRAKESTATE_ERROR_VOLTAGE_ACTIVE 25
#define BRAKESTATE_SETUPACTIVE_END	33
#define BRAKESTATE_ERROR_RETRACT_LOWVOLTAGE 36



//---------------------GLOBAL DEFINITIONS--------------------------
#define EXTENDING 1
#define RETRACTING 2
#define NONE 0
extern uint8_t action;
extern uint8_t motorOn;
//---------------------GLOBAL VARIABLES--------------------------
 
	//---------------------------
	// based on a 100msec 
	//---------------------------
 
//---------------------GLOBAL PROTOTYPES--------------------------
void MotorOff(uint8_t useHoldOff);
void MotorCW(void);
void MotorCCW(void);
void BrakeInit(void);

#endif
